### DAY - 2, 13-4-2023, Thursday

# Python's Library Numpy

In [2]:
import numpy as np

### Array:-

In [7]:
sample_list = [1, 2, 3, 4, 5]
np.array(sample_list)

array([1, 2, 3, 4, 5])

In [5]:
ex_list = [1, 2, 3], [4, 5, 6], [7, 8, 9]
np.array(ex_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Arrange Function:-

In [11]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [17]:
np.arange(0, 51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [18]:
np.arange(5, 26, 5)

array([ 5, 10, 15, 20, 25])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros(5, int)

array([0, 0, 0, 0, 0])

In [23]:
np.zeros(100, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
import numpy as np

In [6]:
np.zeros((2, 5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
np.ones(11, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.ones((3, 3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.linspace(1, 20, 4)

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

### Eye Funtion (Identity Matrix) :-

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye((5), dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
np.eye((2), dtype = int)

array([[1, 0],
       [0, 1]])

In [33]:
np.random.rand(2, 4)

array([[0.36577106, 0.17150858, 0.14327856, 0.79041946],
       [0.31269041, 0.83156878, 0.33923311, 0.19506357]])

### Uniform Distribution :-

In [38]:
arr = np.random.randn(2, 4)
arr

array([[ 1.68017717, -0.15706414, -0.05488322, -0.0715572 ],
       [ 0.05814753,  0.67092912, -0.98087503, -0.90614687]])

In [50]:
np.random.randint(2, 20)

12

In [52]:
np.random.randint(20, 57, 100)

array([31, 43, 48, 48, 43, 45, 41, 29, 33, 24, 37, 52, 50, 22, 40, 40, 30,
       54, 22, 56, 45, 20, 42, 30, 53, 32, 44, 54, 30, 50, 45, 27, 31, 25,
       34, 30, 25, 43, 36, 44, 27, 35, 40, 39, 54, 35, 22, 46, 54, 35, 30,
       32, 39, 38, 55, 39, 28, 52, 32, 43, 37, 48, 29, 42, 29, 34, 53, 38,
       51, 28, 55, 37, 32, 46, 27, 45, 40, 32, 53, 23, 33, 25, 53, 24, 48,
       30, 38, 41, 42, 22, 33, 25, 22, 42, 28, 33, 43, 41, 22, 33])

In [54]:
sample_array = np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [57]:
rand_array = np.random.randint(0, 100, 10)
rand_array

array([78, 46,  4, 79, 76, 51, 68, 58, 17, 40])

In [61]:
sample_array.reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [63]:
sample_array.reshape(3, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [64]:
sample_array.reshape(4, 8)

ValueError: cannot reshape array of size 30 into shape (4,8)

In [65]:
rand_array.min()

4

In [66]:
rand_array.argmin()

2

In [67]:
rand_array.max()

79

In [68]:
rand_array.argmax()

3

In [71]:
a = np.eye((7),dtype = int)
a

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [72]:
a.T

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [77]:
a = np.random.rand(2,5)
a

array([[0.20501487, 0.56725695, 0.79253872, 0.361149  , 0.9341004 ],
       [0.15212176, 0.08702723, 0.24425981, 0.47057034, 0.12011473]])

In [78]:
a.T

array([[0.20501487, 0.15212176],
       [0.56725695, 0.08702723],
       [0.79253872, 0.24425981],
       [0.361149  , 0.47057034],
       [0.9341004 , 0.12011473]])

In [87]:
ex_array = np.arange(10,21)
ex_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [88]:
ex_array[5]

15

In [89]:
ex_array[1:5]

array([11, 12, 13, 14])

In [91]:
ex_array[7:9] = 111
ex_array

array([ 10,  11,  12,  13,  14,  15,  16, 111, 111,  19,  20])

In [92]:
subset_ex_array = ex_array[1:5]
subset_ex_array

array([11, 12, 13, 14])

In [93]:
subset_ex_array[:] = 10000
subset_ex_array

array([10000, 10000, 10000, 10000])

## Two Dimensional Array :-

In [95]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
sample_matrix = np.array(([50, 23, 34, 46],[23, 25, 65, 45],[34, 56, 23 ,78]))
sample_matrix

array([[50, 23, 34, 46],
       [23, 25, 65, 45],
       [34, 56, 23, 78]])

In [104]:
sample_matrix[0][1]

23

In [102]:
sample_matrix[1,3]

45

In [106]:
sample_matrix[2, 1] = 120
sample_matrix

array([[ 50,  23,  34,  46],
       [ 23,  25,  65,  45],
       [ 34, 120,  23,  78]])

In [113]:
sample_matrix[1, :]

array([23, 25, 65, 45])

In [115]:
sample_matrix[2, :] = 1
sample_matrix

array([[50, 23, 34, 46],
       [23, 25, 65, 45],
       [ 1,  1,  1,  1]])

In [116]:
sample_matrix[:,(2,1)]

array([[34, 23],
       [65, 25],
       [ 1,  1]])

In [117]:
sample_matrix[(1,0),:]

array([[23, 25, 65, 45],
       [50, 23, 34, 46]])

## Selection Techniques ;-

In [121]:
sample_array = np.arange(1, 20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [122]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [1]:
import numpy as np

In [3]:
sample_array = np.arange(1, 20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

### Exponential :-

In [4]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

### Square Root:-

In [5]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [29]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

### Standard Deviation:-

In [24]:
np.std(sample_array)

5.477225575051661

### Varience:-

In [16]:
np.var(sample_array)

30.0

### Mean:-

In [17]:
np.mean(sample_array)

10.0

In [10]:
np.min(sample_array)

1

In [11]:
np.argmin(sample_array)

0

In [12]:
np.max(sample_array)

19

In [13]:
np.argmax(sample_array)

18

In [14]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [20]:
array = np.random.randn(2,3)
array

array([[-0.44376582,  0.00321243, -0.4624379 ],
       [-0.69422299, -0.16983974, -0.1844178 ]])

In [21]:
np.round(array, decimals=2)

array([[-0.44,  0.  , -0.46],
       [-0.69, -0.17, -0.18]])

In [23]:
Hobbies = np.array(['Gamming', 'Coding', 'Exploring'])
np.unique(Hobbies)

array(['Coding', 'Exploring', 'Gamming'], dtype='<U9')

In [2]:
print("END")

END
